/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.hmcts;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStream;
import java.util.Properties;
import java.util.Scanner;
import org.apache.commons.io.IOUtils;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.plugins.quality.Checkstyle;
import org.gradle.api.plugins.quality.CheckstyleExtension;
import org.gradle.api.plugins.quality.CheckstylePlugin;
import org.gradle.api.resources.TextResource;
import org.gradle.api.resources.TextResourceFactory;
import org.owasp.dependencycheck.gradle.DependencyCheckPlugin;

/**
 * A simple 'hello world' plugin.
 */
public class JavaPlugin implements Plugin<Project> {
    @lombok.SneakyThrows
    public void apply(Project project) {
        project.getPlugins().apply(CheckstylePlugin.class);
        CheckstyleExtension ext = project.getExtensions().getByType(CheckstyleExtension.class);
        ext.setToolVersion("8.31");

        try (InputStream is = getClass().getClassLoader().getResourceAsStream("hmcts-checkstyle.xml")) {
            Scanner s = new Scanner(is).useDelimiter("\\A");
            String result = s.next();
            File dir = project.file(".config/checkstyle");
            dir.mkdirs();
            File checkstyleConfig = new File(dir, "checkstyle.xml");
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(checkstyleConfig))) {
                writer.write(result);
            }
            for (Checkstyle checkstyle : project.getTasks().withType(Checkstyle.class)) {
                checkstyle.setConfigFile(checkstyleConfig);
            }
        }
    }
}
